name: Build Simplewalker

on:
  push:
    paths-ignore:
      - .github/workflows/build-simplewalker-microcontroller.yml
      - microcontroller/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt install -y libeigen3-dev librapidxml-dev libgtest-dev libwiringpi-dev
      - run: mkdir build
      - name: Configure cmake
        run: cmake ..
        working-directory: ./build

      - name: make test_localization
        run: make test_localization -j$(nproc)
        working-directory: ./build
      - name: Upload test_localization
        uses: actions/upload-artifact@v4
        with:
          name: test_localization
          path: ./build/test/test_localization
          retention-days: 1
          overwrite: true
          if-no-files-found: error

      - name: make collect_sensor_cal_data
        run: make collect_sensor_cal_data -j$(nproc)
        working-directory: ./build

      - name: make simplewalker
        run: make simplewalker -j$(nproc)
        working-directory: ./build

      - run: make unittest_basic_communication -j$(nproc)
        working-directory: ./build
      - run: make unittest_rotation -j$(nproc)
        working-directory: ./build
      - run: make unittest_leg_kinematics -j$(nproc)
        working-directory: ./build
      - run: make unittest_state_prediction -j$(nproc)
        working-directory: ./build
      - run: make unittest_settings -j$(nproc)
        working-directory: ./build
      - name: Upload unit tests
        uses: actions/upload-artifact@v4
        with:
          name: unit_tests
          path: ./build/test/unittest*
          retention-days: 1
          overwrite: true
          if-no-files-found: error

  run_unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download unit tests
        uses: actions/download-artifact@v5
        with: { name: unit_tests }
      - run: mkdir data
      - run: chmod +x ./unittest_basic_communication ./unittest_rotation ./unittest_state_prediction ./unittest_leg_kinematics ./unittest_settings
      - run: ./unittest_basic_communication
      - run: ./unittest_rotation
      - run: ./unittest_state_prediction
      - run: ./unittest_leg_kinematics
      - run: ./unittest_settings


  test_localization:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout settings
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            settings/settings.xml
            settings/localize_test_settings.xml
          sparse-checkout-cone-mode: false
      - name: Download test_localization
        uses: actions/download-artifact@v5
        with: { name: test_localization }
      - run: mkdir data
      - run: chmod +x ./test_localization
      - name: Run test_localization
        run: ./test_localization >> $GITHUB_STEP_SUMMARY
